import os
import math
from collections import Counter
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

def calculate_entropy(data):
    """Calculates the Shannon entropy of the given data"""
    if len(data) == 0:
        print("Warning: Data is empty!")
        return 0.0
    
    byte_frequencies = Counter(data)
    total_bytes = len(data)
    entropy = -sum((freq / total_bytes) * math.log2(freq / total_bytes) for freq in byte_frequencies.values())
    return entropy

def aes_gcm_encrypt(file_data, key):
    # Generate a random IV (Nonce) for GCM mode
    iv = os.urandom(12)  # Recommended IV length for GCM
    
    # Create a cipher object with AES algorithm in GCM mode
    cipher = Cipher(algorithms.AES(key), modes.GCM(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    
    # Encrypt the plaintext
    cipher_text = encryptor.update(file_data) + encryptor.finalize()
    tag = encryptor.tag  # Authentication tag generated by GCM
    
    # Calculate entropy before and after encryption
    plaintext_entropy = calculate_entropy(file_data)
    ciphertext_entropy = calculate_entropy(cipher_text)
    
    print(f"Plaintext entropy before encryption: {plaintext_entropy:.10f} bits per byte")
    print(f"Ciphertext entropy after encryption: {ciphertext_entropy:.10f} bits per byte")
    
    return iv, cipher_text, tag

def read_file(file_path):
    try:
        with open(file_path, "rb") as f:
            return f.read()
    except FileNotFoundError:
        print("Error: File not found!")
        return None
    except OSError as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    # Generate a random 16-byte key for AES
    key = os.urandom(32)
    
    # Get file input from the user
    file_path = input("Enter the full path to the file: ").strip()
    
    # Read the file
    file_data = read_file(file_path)
    
    if file_data:
        file_size = len(file_data)
        print(f"\nTesting with file of size {file_size / 1024:.2f} KB")
        
        # Encrypt the data and print the entropy values
        iv, cipher_text, tag = aes_gcm_encrypt(file_data, key)
